### ISSUE TITLE
page parameter

### ISSUE THREAD

**Issue by timhancock1980** [ahmohamed/NetPathMiner#1]
my version of R 3.01 has no page parameter
it is in 3.0.3
perhaps it should not be used?

**Comment by ahmohamed** [comment]
Honestly, I didn't know it was that recent. I checked the R code, and par("page") is used twice. However, I remember trying other parameters and none gave the desired results.

For the sake of completion, I will give it one more look. Also, this problem will become less pressing since Bioconductor 2.14 requires R >=3.1 anyway.

I also updated the description to indicate dependency on R ( >=3.0.2), where par("page") is present.

**Comment by ahmohamed** [comment]
Closing old issues
